---
driver:
  name: proxy
  host: localhost
  reset_command: "exit 0"
  username: <%= ENV["winrm_user"] %>
  password: <%= ENV["winrm_pass"] %>
  port: <%= ENV["winrm_port"] %>

provisioner:
  name: chef_zero

platforms:
- name: windows-2012R2

verifier:
  name: inspec

suites:
  - name: appveyor-agent-3-12
    run_list:
      - recipe[appveyor-agent-3-12-0::default]
    attributes:
      appveyor:
        access_key: <%= ENV["access_key"] %>
  - name: appveyor-agent-latest
    run_list:
      - recipe[appveyor-agent-latest::default]
    attributes:
      appveyor:
        access_key: <%= ENV["access_key"] %>
  - name: appveyor-deploy-latest
    run_list:
      - recipe[appveyor-deploy-latest::default]
    attributes:
      appveyor:
        access_key: <%= ENV["access_key"] %>
        account: <%= ENV["account"] %>
        api_token: <%= ENV["api_token"] %>
  - name: appveyor-deploy-last-success
    run_list:
      - recipe[appveyor-deploy-last-success::default]
    attributes:
      appveyor:
        access_key: <%= ENV["access_key"] %>
        account: <%= ENV["account"] %>
        api_token: <%= ENV["api_token"] %>
  - name: appveyor-deploy-build-version
    run_list:
      - recipe[appveyor-deploy-build-version::default]
    attributes:
      appveyor:
        access_key: <%= ENV["access_key"] %>
        account: <%= ENV["account"] %>
        api_token: <%= ENV["api_token"] %>
        buildversion: '1.0.2'
