---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
- name: windows-2012r2

verifier:
  name: inspec

suites:
  - name: appveyor-deploy
    run_list:
      - recipe[appveyorapi::default]
    attributes:
      api_token: <%= ENV["api_token"] %>
      environment_access_key: <%= ENV["access_key"] %>
      name: <%= ENV["environment_name"] %>
      project: <%= ENV["project_name"] %>
      account: <%= ENV["account"] %>
