---
driver:
  name: proxy
  host: localhost
  reset_command: "exit 0"
  username: <%= ENV["winrm_user"] %>
  password: <%= ENV["winrm_pass"] %>
  port: <%= ENV["winrm_port"] %>

provisioner:
  name: chef_zero

platforms:
- name: windows-2012R2

verifier:
  name: inspec

suites:
  - name: frontend
    run_list:
      - recipe[clickandcollect-chef::frontend]
    attributes:
      appveyor:
        access_key: <%= ENV["access_key"] %>
        environment_name: <%= ENV["environment_name"] %>
        project_name: <%= ENV["project_name"] %>
        account: <%= ENV["account"] %>
        api_token: <%= ENV["api_token"] %>
        group: 'frontend'
        kitchen: <%= true %>
  - name: backend
    run_list:
      - recipe[clickandcollect-chef::backend]
    attributes:
      appveyor:
        access_key: <%= ENV["access_key"] %>
        environment_name: <%= ENV["environment_name"] %>
        project_name: <%= ENV["project_name"] %>
        account: <%= ENV["account"] %>
        api_token: <%= ENV["api_token"] %>
        group: 'backend'
        kitchen: <%= true %>
  - name: database_ci
    run_list:
      - recipe[clickandcollect-chef::database_ci]
    attributes:
      appveyor:
        access_key: <%= ENV["access_key"] %>
        environment_name: <%= ENV["environment_name"] %>
        project_name: <%= ENV["project_name"] %>
        account: <%= ENV["account"] %>
        api_token: <%= ENV["api_token"] %>
        group: 'database_ci'
        kitchen: <%= true %>
